package org.smartregister.p2p.search.ui

/**
 * Created by Ephraim Kigamba - nek.eam@gmail.com on 02-02-2023.
 */
enum class UIAction {
    SHOW_TRANSFER_COMPLETE_DIALOG,
    NOTIFY_DATA_TRANSFER_STARTING,
    SHOW_CANCEL_TRANSFER_DIALOG,
    SENDER_SYNC_COMPLETE,
    UPDATE_TRANSFER_PROGRESS,
    REQUEST_LOCATION_PERMISSIONS_ENABLE_LOCATION,
    FINISH,
    KEEP_SCREEN_ON,
    PROCESS_SENDER_DEVICE_DETAILS,
    SEND_DEVICE_DETAILS
}
