# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Android CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 30 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Spotless check p2p-lib module
        run: ./gradlew p2p-lib:spotlessCheck
      - name: Show the full path
        run: pwd
      - name: Run unit tests and generate coverage report
        run: ./gradlew p2p-lib:clean && ./gradlew p2p-lib:jacocoTestReport && ./gradlew p2p-lib:coveralls --stacktrace
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
